"""add Transitions

Revision ID: 281f42b6ba99
Revises: 06a3ea51ed03
Create Date: 2025-01-20 20:15:30.759364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '281f42b6ba99'
down_revision: Union[str, None] = '06a3ea51ed03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('level_id')
    )
    op.create_table('transitions',
    sa.Column('transition_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('current_level_id', sa.Integer(), nullable=False),
    sa.Column('action_successful', sa.Boolean(), nullable=False),
    sa.Column('next_level_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_level_id'], ['levels.level_id'], ),
    sa.ForeignKeyConstraint(['next_level_id'], ['levels.level_id'], ),
    sa.PrimaryKeyConstraint('transition_id')
    )
    op.drop_constraint('cards_category_id_fkey', 'cards', type_='foreignkey')
    op.drop_table('categories')
    op.add_column('cards', sa.Column('Level_id', sa.Integer(), nullable=False))
   
    op.create_foreign_key(None, 'cards', 'levels', ['Level_id'], ['level_id'])
    op.drop_column('cards', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key('cards_category_id_fkey', 'cards', 'categories', ['category_id'], ['id'])
    op.drop_column('cards', 'Level_id')
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interval_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    op.drop_table('transitions')
    op.drop_table('levels')
    # ### end Alembic commands ###
