"""add category cards

Revision ID: ab805919a08a
Revises: 6d6c8ee411fa
Create Date: 2025-01-20 19:43:08.376138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab805919a08a'
down_revision: Union[str, None] = '6d6c8ee411fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cards', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cards', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
