"""add last_reviewed culumn

Revision ID: 6de411f1df25
Revises: 2796d00944b6
Create Date: 2025-01-22 08:29:39.015706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de411f1df25'
down_revision: Union[str, None] = '2796d00944b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('last_reviewed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'last_reviewed')
    # ### end Alembic commands ###
