"""rename level name in card

Revision ID: 53e80211c2d1
Revises: 6de411f1df25
Create Date: 2025-01-27 14:37:15.860849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e80211c2d1'
down_revision: Union[str, None] = '6de411f1df25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('level_id', sa.Integer(), nullable=False))
    op.drop_constraint('cards_Level_id_fkey', 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'levels', ['level_id'], ['level_id'])
    op.drop_column('cards', 'Level_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('Level_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key('cards_Level_id_fkey', 'cards', 'levels', ['Level_id'], ['level_id'])
    op.drop_column('cards', 'level_id')
    # ### end Alembic commands ###
